import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2{
            font-size:38px;
          }
          h3{
            font-size:28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span>Hunting Coder</span>
        </h1>
        <div className={styles.imgWrp}>
          <Image className={styles.myimg} src="/home.jpg" alt="an image"  width="410" height="215"/>
        </div>

        <p className={styles.description}>
          A blog for hunting coders by hunting coder
        </p>

        <div className="blogs">
          <h2>Popular blogs : </h2>
          <div className="blogItem">
            <h3>How to learn javascript in 2022</h3>
            <p>JavaScript is a language used to desing logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn python in 2022</h3>
            <p>Python is used mainly in AI and Machine Learning</p>
          </div>
          <div className="blogItem">
            <h3>How to learn java in 2022</h3>
            <p>Java is used as both frontend and backend too</p>
          </div>
        </div>
      </main>
    </div>
  )
}
